on: push

name: DiceyCI

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout-source
        uses: actions/checkout@v3
      - name: simple run
        run: echo Hello World!
